# 常见问题与故障排除

抱歉你在使用 PyO3 时遇到问题。如果在下面的列表中找不到你问题的答案，你也可以在 [GitHub Discussions](https://github.com/PyO3/pyo3/discussions) 和 [Discord](https://discord.gg/33kcChzH7f) 上寻求帮助。

## 我在使用 PyO3 和 lazy_static 或 once_cell 时遇到死锁！

`lazy_static` 和 `once_cell::sync` 都使用锁来确保初始化仅由单个线程执行。由于 Python GIL 是一个额外的锁，这可能导致以下方式的死锁：

1. 一个线程（线程 A）获取了 Python GIL，开始初始化一个 `lazy_static` 值。
2. 初始化代码调用了一些 Python API，这暂时释放了 GIL，例如 `Python::import`。
3. 另一个线程（线程 B）获取了 Python GIL，并尝试访问相同的 `lazy_static` 值。
4. 线程 B 被阻塞，因为它在等待 `lazy_static` 的初始化锁释放。
5. 线程 A 被阻塞，因为它在等待重新获取线程 B 仍然持有的 GIL。
6. 死锁。

PyO3 提供了一个结构体 [`GILOnceCell`]，其功能与 `OnceCell` 相同，但仅依赖 Python GIL 来确保线程安全。这意味着它可以替代 `lazy_static` 或 `once_cell`，在你遇到上述死锁的地方使用。有关如何使用它的示例，请参见 [`GILOnceCell`] 的文档。

[`GILOnceCell`]: {{#PYO3_DOCS_URL}}/pyo3/sync/struct.GILOnceCell.html

## 我无法运行 `cargo test`；或者我无法在 Cargo 工作区中构建：我遇到了链接器问题，如“找不到符号”或“对 _PyExc_SystemError 的未定义引用”！

目前，[#340](https://github.com/PyO3/pyo3/issues/340) 导致在激活 `extension-module` 特性时 `cargo test` 失败并出现链接错误。当在一个不同的 crate 也使用 PyO3 的 Cargo 工作区中构建时，也可能发生链接错误（参见 [#2521](https://github.com/PyO3/pyo3/issues/2521)）。目前，我们可以通过三种方式来解决这些问题。

1. 使 `extension-module` 特性可选。使用 `maturin develop --features "extension-module"` 构建。

```toml
[dependencies.pyo3]
{{#PYO3_CRATE_VERSION}}

[features]
extension-module = ["pyo3/extension-module"]
```

2. 使 `extension-module` 特性可选且为默认。使用 `cargo test --no-default-features` 运行测试：

```toml
[dependencies.pyo3]
{{#PYO3_CRATE_VERSION}}

[features]
extension-module = ["pyo3/extension-module"]
default = ["extension-module"]
```

3. 如果你使用 [`pyproject.toml`](https://maturin.rs/metadata.html) 文件来控制 maturin 设置，请添加以下部分：

```toml
[tool.maturin]
features = ["pyo3/extension-module"]
# 或者对于 maturin 0.12：
# cargo-extra-args = ["--features", "pyo3/extension-module"]
```

## 我无法运行 `cargo test`：我的 crate 在 `tests/` 目录中无法找到进行测试！

Rust 书籍建议将集成测试放在 `tests/` 目录中 [https://doc.rust-lang.org/book/ch11-03-test-organization.html#integration-tests](https://doc.rust-lang.org/book/ch11-03-test-organization.html#integration-tests)。

对于一个 PyO3 `extension-module` 项目，其中 `Cargo.toml` 中的 `crate-type` 设置为 `"cdylib"`，编译器将无法找到你的 crate，并会显示类似 `E0432` 或 `E0463` 的错误：

```text
error[E0432]: unresolved import `my_crate`
 --> tests/test_my_crate.rs:1:5
  |
1 | use my_crate;
  |     ^^^^^^^^^^^^ no external crate `my_crate`
```

最佳解决方案是使你的 crate 类型同时包含 `rlib` 和 `cdylib`：

```toml
# Cargo.toml
[lib]
crate-type = ["cdylib", "rlib"]
```

## 当我的 Rust 代码执行时，Ctrl-C 没有任何反应！

这是因为 Ctrl-C 会引发 SIGINT 信号，该信号由调用的 Python 进程处理，方法是简单地设置一个标志以便稍后采取行动。在从 Python 执行的 Rust 代码运行时，这个标志不会被检查，只有在控制返回到 Python 解释器时才会检查。

你可以通过调用 `Python::check_signals` 给 Python 解释器一个机会来正确处理信号。如果你有一个长时间运行的 Rust 函数，定期调用这个函数是个好习惯，这样你的用户就可以取消它。

## `#[pyo3(get)]` 克隆了我的字段！

你可能有一个类似于以下的嵌套结构体：

```rust
# use pyo3::prelude::*;
#[pyclass]
#[derive(Clone)]
struct Inner {/* fields omitted */}

#[pyclass]
struct Outer {
    #[pyo3(get)]
    inner: Inner,
}

#[pymethods]
impl Outer {
    #[new]
    fn __new__() -> Self {
        Self { inner: Inner {} }
    }
}
```

当 Python 代码访问 `Outer` 的字段时，PyO3 会在每次访问时返回一个新对象（注意它们的地址是不同的）：

```python
outer = Outer()

a = outer.inner
b = outer.inner

assert a is b, f"a: {a}\nb: {b}"
```

```text
AssertionError: a: <builtins.Inner object at 0x00000238FFB9C7B0>
b: <builtins.Inner object at 0x00000238FFB9C830>
```

如果字段是可变的，这可能会特别令人困惑，因为获取字段后进行修改不会持久化 - 你在下次访问时只会得到原始对象的新克隆。不幸的是，Python 和 Rust 对所有权的理解并不一致 - 如果 PyO3 将对（可能是）临时 Rust 对象的引用提供给 Python 代码，Python 代码就可以无限期地保持该引用。因此，返回 Rust 对象需要克隆。

如果你不希望发生这种克隆，可以通过在 Python 堆上分配字段并存储对它的引用来解决，使用 [`Py<...>`]({{#PYO3_DOCS_URL}}/pyo3/struct.Py.html)：

```rust
# use pyo3::prelude::*;
#[pyclass]
struct Inner {/* fields omitted */}

#[pyclass]
struct Outer {
    inner: Py<Inner>,
}

#[pymethods]
impl Outer {
    #[new]
    fn __new__(py: Python<'_>) -> PyResult<Self> {
        Ok(Self {
            inner: Py::new(py, Inner {})?,
        })
    }

    #[getter]
    fn inner(&self, py: Python<'_>) -> Py<Inner> {
        self.inner.clone_ref(py)
    }
}
```

这次 `a` 和 `b` *是*同一个对象：

```python
outer = Outer()

a = outer.inner
b = outer.inner

assert a is b, f"a: {a}\nb: {b}"
print(f"a: {a}\nb: {b}")
```

```text
a: <builtins.Inner object at 0x0000020044FCC670>
b: <builtins.Inner object at 0x0000020044FCC670>
```

这种方法的缺点是，任何处理 `Outer` 结构体的 Rust 代码现在都必须获取 GIL 才能对其字段进行操作。

## 我想使用从依赖项重新导出的 `pyo3` crate，但 proc-macros 失败了！

所有 PyO3 proc-macros（`#[pyclass]`、`#[pyfunction]`、`#[derive(FromPyObject)]` 等）都期望 `pyo3` crate 在你的 crate 根目录下可用，这是当 `pyo3` 是你 crate 的直接依赖时的正常情况。

然而，当依赖项被重命名，或者你的 crate 仅间接依赖于 `pyo3` 时，你需要让宏代码知道在哪里找到该 crate。这是通过 `crate` 属性完成的：

```rust
# use pyo3::prelude::*;
# pub extern crate pyo3;
# mod reexported { pub use ::pyo3; }
# #[allow(dead_code)]
#[pyclass]
#[pyo3(crate = "reexported::pyo3")]
struct MyClass;
```

## 我试图从 Rust 调用 Python，但我得到 `STATUS_DLL_NOT_FOUND` 或 `STATUS_ENTRYPOINT_NOT_FOUND`！

在 Windows 上，当链接到 Python DLL 失败或链接了错误的 DLL 时，会发生这种情况。Windows 上的 Python DLL 通常会被称为：
- `python3X.dll`，用于 Python 3.X，例如 `python310.dll` 用于 Python 3.10
- 当使用 PyO3 的 `abi3` 特性时为 `python3.dll`

该 DLL 需要能够通过 [Windows DLL 搜索顺序](https://learn.microsoft.com/en-us/windows/win32/dlls/dynamic-link-library-search-order#standard-search-order-for-unpackaged-apps) 被找到。实现这一点的一些方法包括：
- 将 Python DLL 放在与构建产物相同的文件夹中
- 将包含 Python DLL 的目录添加到你的 `PATH` 环境变量中，例如 `C:\Users\<You>\AppData\Local\Programs\Python\Python310`
- 如果在 *分发* 程序时发生这种情况，考虑使用 [PyOxidizer](https://github.com/indygreg/PyOxidizer) 将其与二进制文件打包。

如果链接了错误的 DLL，可能是因为另一个程序将自己及其自己的 Python DLL 添加到了 `PATH`。重新排列你的 `PATH` 变量，以优先考虑正确的 DLL。

> **注意**：对 `PATH`（或任何其他环境变量）的更改在现有的 shell 中不可见。重启它以使更改生效。

对于高级故障排除，可以使用 [Dependency Walker](https://www.dependencywalker.com/) 来诊断链接错误。